definitions:
  controllers.GetSearchNotesRequest:
    properties:
      limit:
        description: maximum number of results to return
        example: 10
        type: integer
      offset:
        example: 0
        type: integer
      query:
        description: the query string to search for
        example: Python programming
        type: string
      search_type:
        allOf:
        - $ref: '#/definitions/controllers.SearchType'
        description: the algorithm used to perform the search
        example: context
    required:
    - limit
    - offset
    - query
    - search_type
    type: object
  controllers.MinimalNote:
    properties:
      author_id:
        type: integer
      id:
        type: integer
      stripped_content:
        type: string
      title:
        type: string
      updated_at:
        description: ISO 8601 format
        type: string
    type: object
  controllers.NoteReply:
    properties:
      author_id:
        type: integer
      content:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  controllers.PostNoteRequest:
    properties:
      content:
        example: This is the content of my note.
        type: string
      title:
        example: My Note Title
        type: string
    required:
    - content
    - title
    type: object
  controllers.SearchType:
    enum:
    - context
    - keyword
    - typo_tolerant
    - latest
    type: string
    x-enum-varnames:
    - SearchByContext
    - SearchByKeyword
    - SearchByTypoTolerant
    - SearchByLatest
info:
  contact: {}
  description: Provides all methods to persist data for GoToHell
  title: GoToHell Gin REST API
paths:
  /notes:
    post:
      consumes:
      - application/json
      description: Creates a new Note via gRPC service
      parameters:
      - description: Note ID
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controllers.PostNoteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.NoteReply'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Post a Note
      tags:
      - users
  /notes/{id}:
    get:
      consumes:
      - application/json
      description: Fetch note via gRPC service
      parameters:
      - description: Note ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.NoteReply'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get note by ID
      tags:
      - users
  /notes/search:
    get:
      consumes:
      - application/json
      description: Search notes via gRPC service
      parameters:
      - description: Search Notes Request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controllers.GetSearchNotesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/controllers.MinimalNote'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get notes by search criteria
      tags:
      - users
securityDefinitions:
  CookieAuth:
    in: cookie
    name: discord_auth
    type: apiKey
swagger: "2.0"
